<a href="https://colab.research.google.com/github/Francescolv99/Deep-Video-Deblurring/blob/main/Deep_Video_Deblurring.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
from PIL import Image
import pandas as pd
import os

#dim immagini 720x1280x3
x = []
y = []

In [ ]:
def appendImmagine(filename, x):
    im_1 = Image.open(filename)
    ar = np.array(im_1)
    x.append(ar)
    return x
    

#accedo ad ogni immagine nella cartella qualitative_datasets e le stampo in forma matriciale
def ottieniImmagini(filename, x):
    #apro la cartella del dataset
    entries = os.listdir(filename)
    entries.pop(0)
    #apro ogni sottocartella
    print("LOADING DATASET:")
    for cartella in entries:
        print(cartella)
        lista_cartella = os.listdir(filename + '/'+ cartella)
        lista_cartella.pop(0)
        #lista_cartella è la lista di sottocartelle all'interno di "cartella"
        if(lista_cartella[0]=='input'):
            continue
        else:
            lista_immagini = os.listdir(filename + '/' + cartella + '/' + lista_cartella[1])
            for immagine in lista_immagini:
                if(immagine==".DS_Store"): 
                    continue
                x = appendImmagine(filename + '/' + cartella + '/' + lista_cartella[1] + '/' + immagine, x)
    return x

def ottieniImmaginiTest(filename,x, y):
    #apro la cartella del dataset
    entries = os.listdir(filename)
    entries.pop(0)
    #apro ogni sottocartella
    print("LOADING DATASET:")
    for cartella in entries:
        if(cartella=="input"):
            lista_immagini = os.listdir(filename + '/' + cartella)
            for immagine in lista_immagini:
                if(immagine==".DS_Store"): 
                    continue
                x = appendImmagine(filename + '/' + cartella + '/' + immagine, x)
        elif(cartella==".DS_Store"):
          continue
        else:
            lista_immagini = os.listdir(filename + '/' + cartella)
            for immagine in lista_immagini:
                if(immagine==".DS_Store"): 
                    continue
                y = appendImmagine(filename + '/' + cartella + '/' + immagine, y)
    return x, y

In [ ]:
#x = ottieniImmagini('C:/Users/Gizam/OneDrive/Desktop/DeepVideoDeblurring_Dataset/qualitative_datasets', x)
x,y = ottieniImmaginiTest('/dataset/alley',x,y)
x = np.array(x)
y = np.array(y)
print(x)

LOADING DATASET:
[[[[ 12   9   2]
   [ 12   9   2]
   [ 12   9   2]
   ...
   [ 61  25  11]
   [ 65  29  15]
   [ 68  32  18]]

  [[ 12   9   2]
   [ 12   9   2]
   [ 12   9   2]
   ...
   [ 61  25  11]
   [ 65  29  15]
   [ 67  31  17]]

  [[ 11   8   1]
   [ 12   9   2]
   [ 12   9   2]
   ...
   [ 62  26  12]
   [ 64  28  14]
   [ 66  30  16]]

  ...

  [[ 71  37   0]
   [ 70  36   1]
   [ 68  34   0]
   ...
   [ 52  30   9]
   [ 52  30   9]
   [ 52  30   9]]

  [[ 72  38   1]
   [ 71  37   0]
   [ 70  36   0]
   ...
   [ 52  30   9]
   [ 52  30   9]
   [ 53  31  10]]

  [[ 73  39   2]
   [ 73  39   2]
   [ 72  38   1]
   ...
   [ 52  30   9]
   [ 52  30   9]
   [ 53  31  10]]]


 [[[ 21  11   2]
   [ 22  12   3]
   [ 23  13   4]
   ...
   [ 51  22  14]
   [ 50  21  13]
   [ 50  21  13]]

  [[ 21  11   2]
   [ 22  12   3]
   [ 23  13   4]
   ...
   [ 51  22  14]
   [ 51  22  14]
   [ 51  22  14]]

  [[ 21  11   2]
   [ 22  12   3]
   [ 23  13   4]
   ...
   [ 52  23  15]
   [ 53  24

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [ ]:
print(len(x_train))

206
